import unittest
from scripts.main import *
from scripts.run_scans import *


class TestMain(unittest.TestCase):

    def test_convert_fasta(self):
        with open('test.fasta') as test_handle:
            expected = [['Test1 ', 'AAAAACATCCACGCGCACACGCTGTGCGTTTGAAGTCGCCGCACGCGATCAAGGCGCGGCCGCAACCTATCTGGAACCGTCCGCCAGCCAAATCGGGCACAAAGAAAGCATCAAAGACACGGCGCGCGTCTTGGGCAGAATGTACGATGCCATCGAATATCGCGGCTTCGCTCAGGAAACTGTCGAAGAATTGGCAAAATATGCGGGCGTACCCGTGTTCAACGGGCTGACCAACGAGTTCCATCCCACACAAATGCTTGCCGACGCACTGACTATGCGCGAACACAGCGGCAAACCTTTGAACCAAACCGCGTTTGCCTACGTCGGCGACGCGCGTTACAACATGGGCAATTCCCTGCTGATTTTAGGGGCAAAATTGGGGATGGACGTGCGTATCGGCGCACCTCAAAGCCTGTGGCCGTCTGAAGGCATTATCGCCGCCGCACACGCCGCCGCCAAAGAAACCGGTGCAAAAATTACCCTGACCGAAAACGCGCATGAAGCCGTCAAAGGTGTCGGTTTCATTCATACTGACGTATGGGTCAGCATGGGCGAGCCGAAAGAAGTCTGGCAGGAACGCATCGATTTGCTGAAAGATTACCGCGTTACGCCCGAACTGATGGCGGCATCGGGCAATCCGCAAGTCAAATTCATGCACTGCCTGCCCGCCTTCCACAACCGCGAAACCAAAGTCGGCGAATGGATTTACGAAACCTTCGGGCTGAACGGTGTGGAAGTTACAGAAGAAGTATTCGAAAGTCCGGCCGGCATCGTGTTCGATCAGGCG'],
                        ['Test2', 'AAAAACCTCTACTCGGACGCGCTGCGCGTTTGAAGTCGCCGCGCGCGATCAAGGCGCGGGAGTGACTTATTTAGAGCCGTCCGCCAGCCAAATCGGGCATAAGGAAAGCATCAAAGACACCGCCCGCGTGTTGGGCAGGATGTACGACGGCATCGAATATCGCGGCTTCGCTCAGGAAACTGTCGAAGAATTGACGAAATACGCGGGCGTACCCGTGTTCAACGGGCTGACCAACGAGTTCCATCCCACACAAATGCTTGCCGACGCACTGACTATGCGCGAACACAGCGGCAAACCTTGGAACCAAACCGCGTTTGCCTACGTCGGCGACGCGCGTTACAACATGGGCAATTCCCTGCTGATTTTAGGGGCAAAATTGGGGATGGACGTGCGTATCGGCGCACCGCAAAGCCTGTGGCCGTCTGAAGGCATTATTGCCGCCGCACACGCCGCCGCCAAAGAAACCGGCGCAAAAATTACCCTGACCGAAAACGCGCATGAAGCCGTGAAGAATGTTGATTTTATTCATACCGATGTGTGGGTCAGCATGGGCGAGCCGAAAGAAGTCTGGCAGGAACGCATCGATTTGCTGAAAGATTACCGCGTTACGCCCGAACTGATGGCGGCATCGGGCAATCCGCAAGTCAAATTCATGCACTGCCTGCCCGCCTTCCACAACCGCGAAACCAAAGTCGGCGAATGGATTTACGAAACCTTCGGGCTGAACGGTGTGGAAGTTACAGAAGAAGTATTCGAAAGCCCCGCCAGCATCGTGTTCGATCAGGCG'],
                        ['Test3', 'AAAAACCTCTACTCGGACGCGCTGCGCGTTTGAAGTTGCCGCGCGCGACCAAGGAGCGGGAGTGACTTATTTAGAGCCGTCCGCCAGCCAAATCGGGCATAAGGAAAGCATCAAAGACACTGCCCGCGTATTAGGCAGGATGTACGACGGCATCGAATATCGCGGCTTCGCTCAGGAAACTGTCGAAGAATTGGCGAAATACGCCGGCGTGCCCGTATTCAACGGTCTGACCAACGAGTTCCACCCGACCCAAATGCTCGCCGACGCGCTGACCATGCGTGAACACAGCGGCAAACCTTTGAACCAAACCGCATTTGCCTACATCGGCGATGCGCGTTACAACATGGCGAATTCGCTGCTGGTGTTGGGCGCGAAGCTCGGCATGGACGTGCGTATCGGCGCTCCGAAAACCTTGTGGCCGTCTGAAAACATCGTTGCACGCGCACGCGCCGTTGCCGAAGAAACTGGCGGAAAGATTTTGTTGACCGAAAACACGAAAGAAGCTGTTAAGGGCGCAGATTTTATCCATACCGACGTATGGGTCAGCATGGGCGAGCCAAAAGAAGTATGGCAGGAACGCATTGATTTATTGAAAGATTACCGCGTTACCCCCGAGCTGATGGCGGTATCGGGCAACTCGAAGGTCAAATTCATGCACTGCCTACCCGCCTTCCACAATCGGGAAACCAAAGTCGGAGAATGGATTTATGAAACCTTCGGCTTAAACGGTGTAGAAGTAACGGAAGAAGTATTCGAAAGCCCTGCCAGCATCGTGTTCGACCAAGCG'],
                        ['Test4', 'AAAAACATCGACCCGCACCCGCTGCGCGTTTGAAGTCGCCGCACGTGACCAAGGGGCGGGGGTGACTTATCTGGAGCCGTCCGCCAGCCAAATCAGGCATAAGGAAAGCATCAAAGACACTGCCCGCGTGTTGGGCAGGATGTACGACGGCATCGAATATCGCGGCTTCGGGCAGGACGTGGTCGAAGAATTGGCGAAATACGCCGGCGTGCCCGTGTTCAACGGCTTGACCAACGAGTTCCACCCCACCCAAATGCTCGCCGACGCGCTGACCATGCGCGAACACAGCGGCAAACCCTTGAACCAAACCGCGTTTGCCTACGTCGGCGACGCGCGTTACAACATGGCAAACTCGCTGCTGGTGTTGGGCGCGAAGCTCGGCATGGACGTGCGTATCGGCGCACCGAAAACCTTGTGGCCGTCTGAAAACATCGTCGCCCGCGCCCGCGCCGTCGCCGAAGAAACCGGCGGAAAGATTTTGCTGACCGAAAACGCGGAAGAAGCTGTCAAAGGCGTCGATTTTATCCATACCGACGTGTGGGTCAGCATGGGTGAGCCGAAAGAAGCGTGGCAGGAACGCATTGATTTATTGAAAGATTACCGCGTTACTCCCGAGCTGATGGCGGTATCGGGCAACCCGCAGGTCAAATTCATGCACTGCCTGCCCGCCTTCCACAACCGCGAAACCAAAGTCGGCGAATGGATTTACGAAACCTTCGGCTTAAACGGCGTGGAAGTAACGGAAGAAGTGTTCGAAAGCTCCGCCAGCATCGTGTTCGACCAAGCG']]

            result = convert_fasta(test_handle)
            self.assertEqual(expected, result)

    def test_valid_alignment(self):
        with open('test.fasta') as test_handle:
            aln = convert_fasta(test_handle)
            expected = True
            result = valid_alignment(aln)
            self.assertEqual(expected, result)

            aln2 = [['>Test1', 'ZXCXZATC'],
                    ['>Test2', 'ATGCGGATGGGG']]
            expected = False
            result = valid_alignment(aln2)
            self.assertEqual(expected, result)

    def test_valid_chars(self):
        aln = [['>Test1', 'ZXCXZATC'],
               ['>Test2', 'ATGCGGATGGGG']]
        expected = False
        result = valid_chars(aln)
        self.assertEqual(expected, result)

        aln = [['>Test1', 'TCGCGACGTCAA'],
               ['>Test2', 'ATGCGGATGGGG']]
        expected = True
        result = valid_chars(aln)
        self.assertEqual(expected, result)


class TestRunScans(unittest.TestCase):

    def setUp(self):
        infile = 'CRF07_test.fasta'
        with open(infile) as in_handle:
            aln = convert_fasta(in_handle)

        self.scanner = Scanner(aln, None, infile, run_maxchi=True)

    def test_get_seq_names(self):
        exp_names = ['B', 'C', '07_BC']
        res_names = self.scanner.get_seq_names()
        self.assertEqual(exp_names, res_names)
